### ISSUE TITLE
RuntimeWarning: coroutine 'Command.__call__' was never awaited   else: func(*args, **kwargs)

### ISSUE THREAD

**Issue by Arcanocito** [Defxult/reactionmenu#10]
Hello, I am very excited for the Button Menu and want to thank you a lot for implementing it, I am trying to integrate it right now but when using a caller button I always get this error:

***
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\reactionmenu\buttons_menu.py:570: RuntimeWarning: coroutine 'Command.__call__' was never awaited
  else: func(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
***

The Button was made in this way:
***
g_call_followup = ComponentsButton.Followup()
g_call_followup.set_caller_details(bridgebuy, ctx, "g", menu)
g_caller_button = ComponentsButton(style=ComponentsButton.style.grey, emoji='🏭',label='', custom_id=ComponentsButton.ID_CALLER, followup=g_call_followup)
***

And the Menu was made like this:
***
menu = ButtonsMenu(ctx, menu_type=ButtonsMenu.TypeEmbed, timeout=60, show_page_director=False, all_can_click=False,remove_buttons_on_timeout=True)
***

The Menu starts in the right way and shows the buttons fine, I just cannot use any of my caller buttons, my end session button works fine.

What do I need to change to get it to work >.>

**Comment by Arcanocito** [comment]
Oh ye all my caller buttons call async functions, which is the main problem I guess... the normal emoji reaction menu had no issues with this :/

**Comment by Defxult** [comment]
Is the function you're setting a discord.py command?

**Comment by Arcanocito** [comment]
yes

**Comment by Defxult** [comment]
Ahh, I see the issue. I forgot to add a line in the code. Update to the latest Github version and let me know if it's working now

**Comment by Arcanocito** [comment]
I did the "pip install git+https://github.com/Defxult/reactionmenu.git --upgrade" am kinda new to this, hope that was right. 

The issue sadly still occurs for me

**Comment by Defxult** [comment]
Make sure you uninstall the current version first. And do you have "Git" installed?

**Comment by Arcanocito** [comment]
Ok, uninstalled it first this time and it works fine now! Ty <3

**Comment by Defxult** [comment]
Awesome! Thanks for reporting the issue! 😀 I appreciate it.
