### ISSUE TITLE
Requested feature: Get the context of when the button is pressed.

### ISSUE THREAD

**Issue by Brancieq-Paul** [Defxult/reactionmenu#14]
When you set a button with `custom_id=ComponentsButton.ID_CALLER`, you can set a funtion that execute with that button: 

```
def say_hello(name: str):
    print('Hello', name)
call_followup = ComponentsButton.Followup()
call_followup.set_caller_details(say_hello, 'John')
caller_button = ComponentsButton(style=ComponentsButton.style.red, label='Say Hi', custom_id=ComponentsButton.ID_CALLER, followup=call_followup)
```

But actually, whoever push the button will receive "Hello, John.". What can i do to get the users that push the button name displayed ? I shoulf be able to receive the ctx of when the button is pushed in my `call_followup`, and not only when the menu is created.

Thanks !

**Comment by Defxult** [comment]
This sounds like something [relays](https://github.com/Defxult/reactionmenu#buttonsmenu-relays) do

**Comment by Brancieq-Paul** [comment]
If I have a good understanding, relays do not need ID_CALLER button ? Whichever the button that will be called, relay will be call to ?

**Comment by Brancieq-Paul** [comment]
I tested a little bit, it seems to work well thanks. I thinks I can close here.
