### ISSUE TITLE
After setting the buttons I get the following traceback which seems to be an compatibility issue with discord.py

### ISSUE THREAD

**Issue by SenpaiDesi** [Defxult/reactionmenu#15]
File "C:\Users\DesiDev\AppData\Local\Programs\Python\Python38-32\lib\site-packages\aiofiles\base.py", line 75, in __aenter__
    self._obj = await self._coro
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'linked_to'`

**Comment by Defxult** [comment]
If you're using discord.py 2.0, yes, there's a clash with classes because we both have a `Button` class. Separating the class names should fix the problem
```py
from reactionmenu import Button as RMButton
```
