### ISSUE TITLE
On one server reactionmenu seems to force into ReactionMenu.FAST and button changes stop getting read on page 2

### ISSUE THREAD

**Issue by called2voyage** [Defxult/reactionmenu#22]
**Describe the bug**
I run a bot which uses reactionmenu 2.0.3, and on three servers it works fine in the ReactionMenu.NORMAL mode I have it default to, but on a new server I just added it to, it seems to be forced into ReactionMenu.FAST and will only handle one page flip. Do you know why it might do this? I've included the code below, but again, this works on three out of four servers, so I'm not sure if it will consistently reproduce the error.

For what it's worth, ReactionMenu.FAST still works fine in direct messages to my bot.

**To Reproduce**
Minimal code to reproduce the bug/error
```py
intents = Intents(messages=True, reactions=True, guilds=True, members=True)

# [...]

bot = commands.Bot(command_prefix='!mypronoun ', intents=intents)

# [...]

@bot.command(name='list', help='Lists recognized pronouns')
async def list(ctx):
    menu = ReactionMenu(ctx, back_button='◀️', next_button='▶️', config=ReactionMenu.STATIC)
    pronoun_details = []
    count = 1
    chunk = ''
    for pronoun in pronouns:
        chunk = chunk + pronoun + '\n'
        if count % 10 == 0 or count == len(pronouns):
            embed = Embed(title='Recognized Pronouns')
            page_number = count // 10
            if count % 10 != 0:
                page_number = page_number + 1
            embed.add_field(name='Page ' + str(page_number), value=chunk)
            pronoun_details.append(embed)
            chunk = ''
        count = count + 1
    for pronoun_embed in pronoun_details:
        menu.add_page(pronoun_embed)
    await menu.start()
```

**Traceback if any**
```
N/A
```

**Checklist**
- [x] My Python version is 3.7 or higher
- [x] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled
- [x] This issue is not a duplicate

**Version Info**
What version of the library are you using? `print(reactionmenu.__version__)`
- 2.0.3

**Comment by Defxult** [comment]
Yeah that's really weird. This is the first time anyone has mentioned something like that ever happening, and since it cannot be directly duplicated, I don't know how to fix it. I tried a similar code in a few different servers and it works fine so I'm unsure what could be triggering something like that to happen. If it's in one server, my assumption would be a permission issue (no perms to remove the reaction).

**Comment by called2voyage** [comment]
Finally got a hold of the server admin. It does look like it was a permission issue after all. Sorry for the trouble!
