### ISSUE TITLE
Adding more than one button with type ComponentsButton.style.link makes bot not send message

### ISSUE THREAD

**Issue by nicholasyoannou** [Defxult/reactionmenu#23]
**Describe the bug**
When I attempt to add more than one button with type `ComponentsButton.style.link` the message does not send.
**To Reproduce**
Minimal code to reproduce the bug/error
```
[This code is inside a cog]
[Bot invite links not intended for advertising at all, I haven't removed them so you can fully check everything]
    @commands.command(name='invite')
    async def invite(self, ctx):
        menu = ButtonsMenu(ctx, menu_type=ButtonsMenu.TypeEmbed, show_page_director=False,
                           disable_buttons_on_timeout=True)

        # Link Button
        link_button = ComponentsButton(style=ComponentsButton.style.link, label='Invite',
                                       emoji='<:rimuwu:915340754904289381>',
                                       url='https://discord.com/oauth2/authorize?client_id=836294766651768904&scope=bot&permissions=415538408528&scope=identify%20bot%20applications.commands')

        support_button = ComponentsButton(style=ComponentsButton.style.link, label='SupportServer',
                                          emoji='<:rimuwu:915340754904289381>',
                                          url='https://discord.com/invite/mqez4R2JwM')
        menu.add_button(link_button)
        menu.add_button(support_button)

        Main = discord.Embed(
            title='Invite',
            description="Buttons below testing123")
        menu.add_page(Main)

        await menu.start()
```

**Traceback if any**
```
None, there is no errors that returned in the console. 
```

**Checklist**
- [X] My Python version is 3.7 or higher
- [X] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled
- [X] This issue is not a duplicate

**Version Info**
What version of the library are you using? `print(reactionmenu.__version__)`
Latest version (Python PIP)

**Comment by nicholasyoannou** [comment]
Oh regarding version info, `print(reactionmenu.__version__) returns `2.0.3`

**Comment by Defxult** [comment]
An update has been pushed to GitHub. You'll have to uninstall the current version and pip install the GitHub version (there's an example in the README.md).

P.S: I'm not sure why errors weren't showing for you because I got a traceback when I copy/paste your code. Make sure you're suppressing any errors. Thanks for reporting the issue! 😀
