### ISSUE TITLE
Just need to ask a quick question.

### ISSUE THREAD

**Issue by nicholasyoannou** [Defxult/reactionmenu#25]

**Comment by nicholasyoannou** [comment]
The docs were updated, and I need to update my bot, do we still need .initialize(client) when we're initializing the menu in a cog?

**Comment by Defxult** [comment]
If you're using reactionmenu 3.0 with pycord, no that's not needed anymore. If you're still using version <= v2.0.4, yes it's still needed

**Comment by nicholasyoannou** [comment]
1. Is there a discord server for the reactionmenu addon?
2. `menu = ViewMenu(ctx, menu_type=ViewMenu.TypeEmbedDynamic, rows_requested=7, custom_embed=embed, delete_on_timeout=True)` -- is the following valid?

**Comment by nicholasyoannou** [comment]
> If you're using reactionmenu 3.0 with pycord, no that's not needed anymore. If you're still using version <= v2.0.4, yes it's still needed
> 
> If you still need to access the old docs, they can be found on this [branch](https://github.com/Defxult/reactionmenu/tree/discord-and-dislash)

Also thanks for replying here :)

**Comment by Defxult** [comment]
> 1. Is there a discord server for the reactionmenu addon?
> 2. `menu = ViewMenu(ctx, menu_type=ViewMenu.TypeEmbedDynamic, rows_requested=7, custom_embed=embed, delete_on_timeout=True)` -- is the following valid?

1: No. I don't think the library is big enough to make one
2: Yes, that is valid

**Comment by nicholasyoannou** [comment]
That's all the questions from me. Luckily there isn't much changes compared to the old version so can migrate over quite easily. Just got a lot of files to change and that should be it. Py-cord has changed a lot (I'm very behind), so I'm updating my code slowly slowly according to those changes as well.
Thanks, that's all I need to ask really.

**Comment by nicholasyoannou** [comment]
Just another quick question (no point in opening another one as this thread is just questions). Regarding relays, how do I get the page number? I also want to make it possible when the 'confirm_button' is clicked, then the button menu will close but the original message will be edited.
E.g. a menu is brought up, I click confirm, it logs the page number you were on, the program carries on and the message for that the menu was sent gets edited to a normal text message e.g. 'Hit confirm was successful. Message success edited'. Or something like that.

**Comment by Defxult** [comment]
Relays don't have anything to do with page numbers. All it does is let you know what button was pressed and who pressed it. As for your second part, that doesn't sound like something that involves pagination so I'm not sure if I would implement that. When it comes to finding out what page the menu is on, I could add that. But editing it to a normal message isn't something that would be done on the libraries end. The only thing that comes close to that are `CUSTOM_EMBED` buttons, but those only support embeds, not normal text messages.

**Comment by Defxult** [comment]
Relays don't have anything to do with page numbers. All it does is let you know what button was pressed and who pressed it. As for your second part, that doesn't sound like something that involves pagination so I'm not sure if I would implement that. When it comes to finding out what page the menu is on, that's handled internally to control the pagination process. Editing it to a normal message isn't something that would be done on the libraries end. The only thing that comes close to that are `CUSTOM_EMBED` buttons, but those only support embeds, not normal text messages.

**Comment by nicholasyoannou** [comment]
Another question, sorry about these! Is there a way for a menu to be opened, the task stops until an option is picked in the menu, and then the code continues? What my code currently does is opens the menu and continues down the code, which is not what I want as the user picking an option in the button embed effects what happens next.

**Comment by nicholasyoannou** [comment]
Looks like I can't reopen this, will open a new issue

**Comment by Defxult** [comment]
You have to be more clear. Provide an example because reading that was...confusing.

**Comment by nicholasyoannou** [comment]
So basically,

```
menu.set_relay(confirm)
await menu.start()
```
I set up my menu and do await menu.start() (for starting the menu).
But in my set_relay when they click 'confirm':

```
        async def confirm(payload):
            buttonpressed = payload.button.label
            if buttonpressed == 'Confirm':
                confirm.variable = que_temp[1]
                menu.remove_all_buttons()
                await menu.stop(delete_menu_message=True)
```
...the menu stops. Which is when I want the code to continue. 

...if that makes any sense?

**Comment by Defxult** [comment]
If you call stop `.stop()`, then the menu will stop. There’s no code that can continue after the menu has been stopped.

**Comment by nicholasyoannou** [comment]
Ok let me try and rephrase: so basically the code will continue once the menu has been closed. So let’s say in my relay I record how many times a button has been pressed. I want that to be sent after the menu is closed, so basically what I’m saying is for a way for code after when my menu is opened to be executed once the menu is closed.

**Comment by Defxult** [comment]
Yes, code can be executed once the menu is closed. But interaction with the menu itself cannot occur.

**Comment by nicholasyoannou** [comment]
> Yes, code can be executed once the menu is closed.
How do I do this? Is there a wait_until_closed or something like that?

**Comment by Defxult** [comment]
Ahh, so I think I know what you mean. So:
>  wait_until_closed or something like that?

After calling `menu.stop()`, you want code somewhere else to execute *because* the menu got closed. 

Reading this line:
> so basically what I’m saying is for a way for code after when my menu is opened to be executed once the menu is closed.

No, there's no way to execute code after the menu has been closed. Just to be 100% sure, you're looking for something like `on_menu_close()`  correct?

**Comment by nicholasyoannou** [comment]
Yup, or even `menu.wait_until_closed()` would be great.

**Comment by Defxult** [comment]
Yeah those aren’t in the library at the moment. Shouldn’t be too hard to add them in the next version though

**Comment by Defxult** [comment]
@nicholasyoannou `menu.wait_until_closed()` has been added. Update to [v3.0.1](https://github.com/Defxult/reactionmenu/blob/main/CHANGELOG.md) for the new feature

**Comment by nicholasyoannou** [comment]
Eyyy that’s great! Just in case for others that are looking at this (and as a note to self) and don’t want to update, I used ‘menu.is_closed’ and did an if check (inside a while loop to check every second) to check if it was closed. If it was then it’d return a timeout error.

**Comment by nicholasyoannou** [comment]
(Uh it said in the changelog you added it for reaction menus but I use button menus)

**Comment by Defxult** [comment]
![D36B627F-7C59-4AAE-83A8-BD6DF1B88000](https://user-images.githubusercontent.com/52070034/152187220-75767312-07d1-4841-901f-23a198134b74.jpeg)

I don’t type it twice. I just specify at the top and type `ReactionMenu` for everything unless only for `ViewMenu`. It’s the same format as the 3.0.0 changelog

**Comment by nicholasyoannou** [comment]
My bad for not noticing, yup, sounds good!

**Comment by Defxult** [comment]
There are no videos in the embed. They are either images or a link

**Comment by nicholasyoannou** [comment]
Another suggestion! Can you add as an alternative to `disable_buttons_on_timeout`, it'd be great if we could have `delete_buttons_on_timeout` -- would this be possible?

**Comment by Defxult** [comment]
That already [exists](https://github.com/Defxult/reactionmenu#kwargs-of-the-viewmenu-constructor)
```py
menu = ViewMenu(ctx, ...)
menu.remove_buttons_on_timeout = True
menu.disable_buttons_on_timeout = False
```
