### ISSUE TITLE
Remove_buttons_on_timeout doesn't work

### ISSUE THREAD

**Issue by nicholasyoannou** [Defxult/reactionmenu#28]
**Describe the bug**
remove_buttons_on_timeout doesn't work.

**To Reproduce**
Minimal code to reproduce the bug/error
```py
menu = ViewMenu(ctx, menu_type=ViewMenu.TypeEmbed, name='idk', show_page_director=False, remove_buttons_on_timeout=True)
```

**Traceback if any**
None

**Required Checklist**
- [X] My Python version is 3.8 or higher
- [X] I am using reactionmenu v3.0 or higher
- [X] I am using Pycord v2.0 or higher
- [X] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled

**Version Info**
What version of the library are you using? `print(reactionmenu.version_info())`
- Latest GitHub version. (VersionInfo(version='3.0.1', releasetype='final', patch='1a'))

What version of Pycord are you using? `print(discord.__version__)`
- Latest GitHub version. (2.0.0b4)

**Comment by Defxult** [comment]
You did not follow my example provided [here](https://github.com/Defxult/reactionmenu/issues/25#issuecomment-1038340050)…

**Comment by nicholasyoannou** [comment]
I did, I was going to reply that I tried it but ....you locked the thread 😓

**Comment by nicholasyoannou** [comment]
Nevermind! Was being a idiot and forgot to put both parameters in (disable_buttons_on_timeout=False as well as remove_buttons_on_timeout=True in ViewMenu).

**Comment by nicholasyoannou** [comment]
Another quick query, not sure if it's a user error so am putting it here.

I tried starting a menu, however I got a 400 error when starting the menu. Here's a DEBUG (logging module - DEBUG) log, hopefully it's sufficient info from for diagnosis.

```
DEBUG:discord.http:POST https://discord.com/api/v9/channels/934159991923933184/messages with {"embeds":[{"type":"rich","description":"Your a new user who has never subscribed before to sub notifications, welcome! <:RimuHug:915350019001958452>\nPlease select whether you'll like for your anime subscription history to have it stored as Romaji, or English. Of course, you can opt out so subscription history is not stored. If no option is picked, the bot will automatically opt out for anime notifications.","title":"New user detected"}],"allowed_mentions":{"replied_user":true,"parse":["everyone","users","roles"]},"components":[{"type":1,"components":[{"type":2,"style":2,"label":"Romaji","disabled":false,"custom_id":"6_1363083470016","emoji":{"name":":flag_jp:"}},{"type":2,"style":2,"label":"English","disabled":false,"custom_id":"6_1363083470880","emoji":{"name":":england:"}},{"type":2,"style":2,"label":"Opt-out","disabled":false,"custom_id":"6_1363083470928","emoji":{"name":"arrow_back","id":919160982629146644}}]}]} has returned 400
```
