### ISSUE TITLE
Links as buttons - issue with expiry/deletion (prevent disabling/removal)

### ISSUE THREAD

**Issue by nicholasyoannou** [Defxult/reactionmenu#29]
Hi, just a little query with buttons.

Just with links: if I have links as buttons, that doesn't send a request back to my bot (rate limit friendly), so how do I make it so the buttons don't ....expire/get disabled/get deleted? Or is this not yet possible for link buttons?

(PS: If you hate me creating issues on GitHub, you can add me (janeberru#four five nine four) through Discord)

**Comment by nicholasyoannou** [comment]
Okay, guess for the time being I’ll have to use Pycord directly

**Comment by Defxult** [comment]
You bring up a good point though. I don’t see a reason why they should be disabled/removed when they aren’t directly affecting the menu when it has stopped. I’ll figure out a way to prevent that because that’s something I totally overlooked. Thanks for bringing it up

**Comment by Defxult** [comment]
@nicholasyoannou This has been added to the library. Please uninstall your current version then install the GitHub version. You can take a look at the [changelog](https://github.com/Defxult/reactionmenu/blob/main/CHANGELOG.md) to see what's needed to use this functionality.

**Comment by nicholasyoannou** [comment]
That’s great, thanks for adding to the README file as well so will look at that at some point. For the time being for simple views (button embeds in my case) I’ll just directly use the Pycord library as it’s literally only a few small lines of code; I use reactionmenu for anything that requires pagination or anything complex, so thanks for letting me rely on your library for that :)
