### ISSUE TITLE
Update docs to reflect required Python version

### ISSUE THREAD

**Issue by called2voyage** [Defxult/reactionmenu#3]
I just started using reactionmenu in one of my Discord bots today, and I had trouble running it in Python 3.6. I updated to Python 3.9 and it worked fine. I did some digging and it turns out the issue is with the create_task method. You use the name parameter that wasn't added until 3.8. So it should work fine with Python 3.8+, but anything earlier will run into that error. Just thought you should know so you can update the docs--not expecting a fix for earlier versions.

**Comment by Defxult** [comment]
In `v1.0.9`, the `name` parameter was removed from all `create_task`, but who knows when I might use it again in the future or any other Python 3.8+ features. It's always a good idea to show what version of Python is needed in order for the package to work properly. I will update the docs. Thank you! 👍

**Comment by called2voyage** [comment]
I could have sworn I saw name used in one line of 1.0.9, but you're right I don't see it now. Thanks for adding the version note anyway!
