### ISSUE TITLE
Is it possible to restart a ViewMenu after it times out? 

### ISSUE THREAD

**Issue by Meschdog18** [Defxult/reactionmenu#30]
Is it possible to restart a viewmenu after times out, so that the buttons are accessible again?

**Comment by Defxult** [comment]
It is not possible. It not being possible isn't on the libraries end though, it's because the discord interaction would have ended and you can't restart it once it's stopped.

**Comment by Jordan-Mesches** [comment]
I actually got it to "restart" by just subclassing the viewmenu, than writing a restart function that just sets timed out to false, and is running to true, than it appends to active sessions and refreshes and enables the buttons.

**Comment by Jordan-Mesches** [comment]
I replied on the wrong account lol
