### ISSUE TITLE
reactionmenu - discord.py 2.0 update

### ISSUE THREAD

**Issue by Defxult** [Defxult/reactionmenu#32]
As a lot of you may know [discord.py](https://github.com/Rapptz/discord.py) has [continued development](https://gist.github.com/Rapptz/c4324f17a80c94776832430007ad40e6). Right now this library operates on a fork of it, but will it change back to discord.py? Yes it will. The future update (`v3.1.0`) will have some breaking changes, additions, and things that have been removed. reactionmenu `v3.1.0` will not be released until discord.py 2.0 is officially released. 

In the mean time, ~~I will be posting updates here for when `v3.1.0` is ready to be tested.~~ If you plan on changing back to discord.py like I am and are planning on using this library, I hope you can join me in testing when it becomes available.

Thank you!

### Edit - March 22, 2022
reactionmenu `v3.1.0` is now available for testing. Updates will not be posted here, please visit the [v3.1.0 branch](https://github.com/Defxult/reactionmenu/tree/discord.py-2.0-support) for further information.

**Comment by vikasbhatia** [comment]
Hi!

Your lib looks great and I'm very happy you've decided to support discord.py (I was partyway through switching to Pycord when it was announced that discord.py was resuming development).

I'm very keen to start using it to make a button paginator. What's the soonest I can get my hands on it? (asking because I have no idea when discord.py is officially going to release 2.0...even if I get a pre-release version of yours, I can start integrating it into my bot). I'm of course happy to test/provide feedback on whatever I use.

Thanks!

**Comment by Defxult** [comment]
The earliest would be probably Saturday (Mar. 26, 2022). I’m trying to develop it along side discord.py, so any changes they introduce that affects my library I can fix quickly instead of waiting for it to finish then having to catch up. But I’ve been making progress.

I appreciate you saying that will help in testing! I test the lib inside and out but I’m only one person so I always miss something here and there.

**Comment by vikasbhatia** [comment]
Thanks for responding - Saturday sounds good! Would you mind if I reached out to you on Discord directly to talk?

**Comment by Defxult** [comment]
I was planning on opening a “Discussion” so we can talk there. It’s disabled at the moment because there was no need for it, but now that d.py 2.0 is going to release, I’d want to have somewhere anyone can contact me about issues quickly without opening a new “Issue” every time when it comes to testing before release.

**Comment by vikasbhatia** [comment]
That works too, thanks.

Also I'm sure you're likely aware of this, but I was told on the r/Discord_Bots server that the latest on the master branch of discord.py right now is pretty close to what the actual release is going to be, so barring some minor changes, that'll probably be what we get. FWIW I thought I'd pass the info along.

**Comment by Defxult** [comment]
reactionmenu `v3.1.0` is now [available](https://github.com/Defxult/reactionmenu/tree/discord.py-2.0-support) for testing.
