### ISSUE TITLE
Invalid custom emoji

### ISSUE THREAD

**Issue by gaurishhs** [Defxult/reactionmenu#37]
**Describe the bug**
I'm trying to use a custom emoji for the ViewButton but it always Invalid emoji, In the example below i try the partial emoji but if i pass just the simple emoji string, it would throw the same error. 
Also, i have tried check the emojis are not none

**To Reproduce**
Minimal code to reproduce the bug/error
```py
leftArrow = discord.PartialEmoji.from_str(self.client.config['emojis']['left_arrow'])
rightArrow = discord.PartialEmoji.from_str(self.client.config['emojis']['right_arrow'])
back_button = ViewButton(style=discord.ButtonStyle.secondary, emoji=leftArrow, custom_id=ViewButton.ID_PREVIOUS_PAGE)
next_button = ViewButton(style=discord.ButtonStyle.secondary, emoji=rightArrow, custom_id=ViewButton.ID_NEXT_PAGE)
```

**Traceback if any**
```
HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In components.0.components.0.options.0.emoji.name: Invalid emoji
In components.0.components.0.options.1.emoji.name: Invalid emoji
In components.0.components.0.options.2.emoji.name: Invalid emoji
In components.0.components.0.options.3.emoji.name: Invalid emoji
In components.0.components.0.options.4.emoji.name: Invalid emoji
In components.0.components.0.options.5.emoji.name: Invalid emoji
In components.0.components.0.options.6.emoji.name: Invalid emoji
In components.0.components.0.options.7.emoji.name: Invalid emoji
In components.0.components.0.options.8.emoji.name: Invalid emoji
```

**Required Checklist**
- [x] I am using discord.py 2.0 or higher
- [x] I am using reactionmenu 3.1.0 or higher
- [x] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled

**Version Info**
What version of reactionmenu/discord.py are you using?
- reactionmenu: 3.1.0
- discord.py: 2.0.0

**Comment by Defxult** [comment]
I'm not sure why it's causing that error because on my end, this error cannot be duplicated. This is the code I am testing that's similar to yours:
```py
@bot.command()
async def abc(ctx: commands.Context):
    menu = ViewMenu(ctx, menu_type=ViewMenu.TypeEmbed)
    menu.add_pages([discord.Embed(title='1'), discord.Embed(title='2')])

    leftArrow = discord.PartialEmoji.from_str('<:left:819869338646478928>')
    rightArrow = discord.PartialEmoji.from_str('<:right:819869352702378044>')

    back_button = ViewButton(style=discord.ButtonStyle.secondary, emoji=leftArrow, custom_id=ViewButton.ID_PREVIOUS_PAGE)
    next_button = ViewButton(style=discord.ButtonStyle.secondary, emoji=rightArrow, custom_id=ViewButton.ID_NEXT_PAGE)
    menu.add_buttons([back_button, next_button])
    
    await menu.start()
```
And this is the result:

![test results](https://user-images.githubusercontent.com/52070034/187045022-25e87675-c19f-48a4-8db7-20c3def86d88.gif)

Is the emoji you a trying to get via `self.client.config['emojis']['left_arrow']` formatted correctly in the way `discord.PartialEmoji` expects?

**Comment by gaurishhs** [comment]
@Defxult Also, one more thing in the .go_to_select thing can't we have both emojis and label at the same time?

**Comment by Defxult** [comment]
You can, that is all [documented](https://github.com/Defxult/reactionmenu#go-to-page-navigation). Please note that GitHub doesn't auto expand the section, so you'll have to expand it first, then navigate to "Go to page navigation" (I'd just use Ctrl + F) after expanding

**Comment by gaurishhs** [comment]
> You can, that is all [documented](https://github.com/Defxult/reactionmenu#go-to-page-navigation). Please note that GitHub doesn't auto expand the section, so you'll have to expand it first, then navigate to "Go to page navigation" (I'd just use Ctrl + F) after expanding

Can't see an example for that, Is it to be done like this?

```py
page_numbers={1 : "🗯️ Label", 2 : "📺 label"}
```

**Comment by Defxult** [comment]
Yes.

**Comment by Defxult** [comment]
But only the emoji. Not text and an emoji

**Comment by gaurishhs** [comment]
Alright, Thanks!
