### ISSUE TITLE
Documentation for Dm pagination 

### ISSUE THREAD

**Issue by vichubenzene** [Defxult/reactionmenu#41]
The `send_to` feature for the `Users Dm with id` is not documented well. If its implemented, can I know the function usage of it.

**Comment by Defxult** [comment]
For `send_to`, the documentation states "The **channel**/**thread** you'd like the menu to start in", meaning sending it to a user is not an option. Only channels or threads. If you have DMing your bot enabled, the user can message the bot and it will work that way. The user can DM the bot, and the menu will be available in their DMs on `.start()`

**Comment by vichubenzene** [comment]
Thank You for your time. 👍
