### ISSUE TITLE
Getting a page index and/or buttons per page?

### ISSUE THREAD

**Issue by TheClassicalGod** [Defxult/reactionmenu#43]
I'm not sure if these things are already possible. I haven't been able to figure out a good way of doing it myself, but is it possible to be able to get the page index or something to that effect after it has been started? Being able to set buttons per page would also go a long way in helping with this, I think. Though there may be other ways that I'm not smart enough to figure out.

The goal is to have a menu that has multiple layers of depth. In my case, grabbing info from an API, sorting it, putting info into embed that get used as pages. This much works great, but falls a little short of what I'm trying to do.

Personally, I'm looking to be able to have each page have a button or way of selecting something within that initial page and having said button know which page it's on so I can match the index to the initial list that built the embeds to begin with and use that to run more another function or external script on the local machine the bot is running on, etc... 

I know it's likely super edge case and not a thing many are looking for, but the basic concept would allow for tons of different things to stem from it, including some full on turn based games.

**Comment by TimBritcliffe** [comment]
you're actually able to get reactionmenu to work? lol I can't even import it despite installing it on my device properly.

**Comment by TimBritcliffe** [comment]
But in reference to what you are looking for. Do you mean you want pagination and then also have it so that each page has it's own buttons with it's own functionality?

**Comment by TheClassicalGod** [comment]
> you're actually able to get reactionmenu to work? lol I can't even import it despite installing it on my device properly.

Yup. It had other dependencies that didn't install on it's own (typing_extensions? I think that was the one.), but it worked fine after installing that through pip. If you're getting import errors, it may or may not because of that?

> But in reference to what you are looking for. Do you mean you want pagination and then also have it so that each page has it's own buttons with it's own functionality?

Basically, yeah. An example would be maybe a pokedex. Creating objects for pokemon with all of their information, but only some of it being used at once. Single pokemon per page, but to get different information (difference per generation, etc...), you need to know what page is in use and know what button was pressed to call back to get new information to create a new embed to update with.

That example is an ideal case with matching types of information for each object. Other examples would be similar for say... a music bot needing to select songs, or a personal file downloader searching an API, pages for each result, each page has different mirrors or file types or whatever really to choose from that require a differing number and/or labeling of buttons to select from. That last one is definitely an edge case that shouldn't be used on a public server or at least have restrictions on, lol, but is definitely doable.

I know all of these things can be done purely with text since I've done it. I just think reactionmenu is a far more aesthetically pleasing and friendly to a random person that doesn't want to memorize or fumble through commands and at least 90% of what I wanted to do is already there.

There's also the possibility that everything I want is already there and I'm just an idiot that doesn't understand everything I read when it comes to documentation. lol

**Comment by Defxult** [comment]
> you're actually able to get reactionmenu to work? lol I can't even import it despite installing it on my device properly.

Problems installing should be fixed as of v3.1.2

As for the *issue*, I've thought about adding something of that sort, but the use case is so minimal I don't see the point in adding it

**Comment by TimBritcliffe** [comment]
> Yup. It had other dependencies that didn't install on it's own (typing_extensions? I think that was the one.), but it worked fine after installing that through pip. If you're getting import errors, it may or may not because of that?

How did you go about installing typing_extensions? Did you just type pip install typing_extensions?

**Comment by Defxult** [comment]
> How did you go about installing typing_extensions? Did you just type pip install typing_extensions?

If you do `pip install discord.py`, it also installs typing extensions because discord.py utilizes that library.

But if you need to install it urself, it's `pip install typing-extensions`

**Comment by JDJGInc** [comment]
> > How did you go about installing typing_extensions? Did you just type pip install typing_extensions?
> 
> If you do `pip install discord.py`, it also installs typing extensions because discord.py utilizes that library.
> 
> But if you need to install it urself, it's `pip install typing-extensions`

I know this an old issue, however someone had an issue installing it today because discord.py doesn't have a builtin typing-extenstions

**Comment by ameyanori** [comment]
Above was my issue, it was also suggested that typing-extensions shouldnt be a runtime dependency.

such that:

```
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from typing_extensions import Self
```
