### ISSUE TITLE
Support for sending menu to direct message

### ISSUE THREAD

**Issue by called2voyage** [Defxult/reactionmenu#5]
Would you consider adding support for sending the menu to a direct message? One of my users seems to have attempted that, and if there's interest in using that way I'd like to support that if possible. Currently reactionmenu receives a None type for guild when a user invokes it via direct message, which causes an error.

**Comment by Defxult** [comment]
I've thought about doing it, but never really thought of a use case for it. I suppose I don't really see a reason for it to not work in DM's though. I'll do some testing with it and if there aren't any big issues with implementing it, I'll add support for it.

**Comment by vichubenzene** [comment]
Ig the ` send_to ` feature for the **Users Dm with id** is not documented well. If its implemented, can I know the function usage of it.

**Comment by martinbndr** [comment]
Would it also be possible to implement sent_to can be used to adda discord.User or discord.Member?
The paginator would get sent in the user dm`s and can use the paginator there.

Usecase:
Created a normal message command that can be used in a server, the information given in the sent message should be kept private in direct messages.
