### ISSUE TITLE
Ephemeral response for paginated menus missing?

### ISSUE THREAD

**Issue by skylarr1227** [Defxult/reactionmenu#56]
### Describe the bug

I see no way to make a paginated menu ephemeral.  Am i just missing it?
Specifically when using the `.next` and `.back` buttons.

### Minimal Reproducible Code

```python
menu = ViewMenu(interaction, menu_type=ViewMenu.TypeEmbed)
embed = discord.Embed(description=response_content)
menu.add_page(embed)
buttons = [ViewButton.back(), ViewButton.next()]
for btn in buttons:
    menu.add_button(btn)
await menu.start()
```

### Traceback

```txt
None
```

### Library Version

- Python v3.12.1-final
- discord.py v2.3.2-final

### Required Checklist

- [X] I am using discord.py 2.0 or higher
- [X] I am using reactionmenu 3.1.0 or higher
- [X] I have the required [intents](https://github.com/Defxult/reactionmenu#intents) enabled

### Additional Comments

I apologize if this is not the place, however I don't see anywhere else to ask. Maybe a discord? Thanks in advance.

**Comment by Defxult** [comment]
There's no implementation of it.
