### ISSUE TITLE
Reactionmenu requiering "Manage messages" permission.

### ISSUE THREAD

**Issue by Arcanocito** [Defxult/reactionmenu#8]
The current reactionmenu requires the Manage messages permission since it mandatorily tries to remove reactions, immediately crashing the menu after turning a page if the permission is not given. 
Voting sites such as Top.gg require you to not need these permissions for your bot to work, so this would be a problem since most of my menus are now made using this package, which I am very grateful for and love using. 

Could there be an attribute or something similar added to the constructor to not require this permission for the menus to work?

**Comment by Defxult** [comment]
There are already attributes (kwargs) available in the constructor to bypass the manage messages permission. You can change the `navigation_speed`, `clear_reactions_after`, and `delete_interactions` to not require that permission for the menu to work.

```py
menu = ReactionMenu(..., navigation_speed=ReactionMenu.FAST, clear_reactions_after=False, delete_interactions=False)
```
You can take a look at the [ReactionMenu kwargs](https://github.com/Defxult/reactionmenu#options-of-the-reactionmenu-constructor-kwargs) for an explanation for what those kwargs do, but those settings will avoid the manage messages permission.

**Comment by Arcanocito** [comment]
Thank you, I always tried them individually not all at once, ty for the quick help!
