### ISSUE TITLE
Issue with paginating in DMs.

### ISSUE THREAD

**Issue by ReddKarma** [Defxult/reactionmenu#9]
I noticed that this doesn't support dm channels and instead looks specifically for text channels, could you perhaps allow it to support both ?

**Comment by ReddKarma** [comment]
nevermind I just noticed it works with the new updated version, however the next and previous buttons don't seem to do anything when pressed, i'm using the ReactionMenu.STATIC btw.

**Comment by Defxult** [comment]
Read the conversation in issue #6 and let me know if the problem persists

**Comment by ReddKarma** [comment]
Ah it works now thank you, much love.
